src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\Column(type: 'string', length: 60)]
    private $last_name;

    #[ORM\Column(type: 'string', length: 60)]
    private $first_name;

    #[ORM\OneToMany(mappedBy: 'owner', targetEntity: Magazine::class)]
    private $magazines;

    public function __construct()
    {
        $this->magazines = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    /**
     * @return Collection<int, Magazine>
     */
    public function getMagazines(): Collection
    {
        return $this->magazines;
    }

    public function addMagazine(Magazine $magazine): self
    {
        if (!$this->magazines->contains($magazine)) {
            $this->magazines[] = $magazine;
            $magazine->setOwner($this);
        }

        return $this;
    }

    public function removeMagazine(Magazine $magazine): self
    {
        if ($this->magazines->removeElement($magazine)) {
            // set the owning side to null (unless already changed)
            if ($magazine->getOwner() === $this) {
                $magazine->setOwner(null);
            }
        }

        return $this;
    }

}

src/Controller/UserController.php
<?php

namespace App\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[IsGranted('ROLE_USER')]
class UserController extends AbstractController
{
    #[Route('/account', name: 'app_user')]
    public function index(): Response
    {
        return $this->render('user/index.html.twig', [
        ]);
    }
}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello User !{% endblock %}

{% block body %}

        <!-- Contenu -->
        <main class="p-4">
            <div class="container">
                <div class="row">
                    <div class="col-12 d-flex">
                        <div class="col-11 d-flex text-start">
                                <h2 class="fs-3 text-danger">Vos informations</h2>
                        </div>
                        <div class="col-1 d-flex justify-content-end">
                            <a href="{{ path('app_home') }}" class="btn btn-outline-danger my-auto">retour</a>
                        </div>
                    </div>
                    <div class="col-12 d-block border-bottom my-3"></div>
                    <div class="col-12 d-flex mt-1">
                        <div class="col-1 m-auto">
                            <p class="fw-bold text-center text-secondary">#</p>
                        </div>
                        <div class="col-3 m-auto">
                            <p class="fw-bold text-center">Nom</p>
                        </div>
                        <div class="col-3 m-auto">
                            <p class="fw-bold text-center">prénom</p>
                        </div>
                        <div class="col-3 m-auto">
                            <p class="fw-bold text-center">Adresse email</p>
                        </div>
                        <div class="col-2 m-auto">
                            <p class="fw-bold text-center">Actions</p>
                        </div>
                    </div>
                    <div class="col-12 d-block border-bottom mb-2"></div>
                        <div class="col-12 d-flex mb-3 mt-2 border-bottom">
                            <div class="col-1 m-auto">
                                <p class="text-center text-secondary">{{app.user.id}}</p>
                            </div>
                            <div class="col-3 m-auto">
                                <p class="text-center text-secondary">{{app.user.lastName}}</p>
                            </div>
                            <div class="col-3 m-auto">
                                <p class="text-center text-secondary">{{app.user.firstName}}</p>
                            </div>
                            <div class="col-3 m-auto">
                                <p class="text-center text-secondary">{{app.user.email}}</p>
                            </div>
                            <div class="col-2 d-flex justify-content-center pb-3">
                                <a href="# {# {{ path('app_user_edit', {id:app.user.id}) }} #}" class="btn btn-outline-success m-auto">Modifier</a>
                            </div>
                        </div>
                    </div>
                </div>
            </main>

{% endblock %}